### ISSUE TITLE
"non-latin" characters in file names cause UnicodeEncodeError

### ISSUE THREAD

**Issue by bbjubjub2494** [lourkeur/httpshare#8]
attempting to download a file with a character not covered by the iso-8859-1 charset, results in a 304 with this type of traceback:
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/usr/lib/python3.7/wsgiref/handlers.py", line 184, in finish_response
    self.write(data)
  File "/usr/lib/python3.7/wsgiref/handlers.py", line 287, in write
    self.send_headers()
  File "/usr/lib/python3.7/wsgiref/handlers.py", line 346, in send_headers
    self._write(bytes(self.headers))
  File "/usr/lib/python3.7/wsgiref/headers.py", line 142, in __bytes__
    return str(self).encode('iso-8859-1')
UnicodeEncodeError: 'latin-1' codec can't encode character '\u0152' in position 43: ordinal not in range(256)
```

Unsure if this charset is picked by default or by my locale atm. Will investigate.

It is most likely the real ISO codec rather than Microsoft CP-252 (they get confused for each other all the time) based on the [Python documentation.](https://docs.python.org/3.5/library/codecs.html#encodings-and-unicode)

**Comment by bbjubjub2494** [comment]
Only happens with Python 3, and got fixed by https://github.com/bottlepy/bottle/issues/1148. I was using 1.0.6 yesterday which doesn't have that fix. Solution: just update because it's fixed in 1.0.7.
